UPDATE applications
SET
    name = $2,
    is_active = $3,
    workspace_template = $4,
    default_shell = $5,
    default_scopes = COALESCE($6, default_scopes),
    max_timeout_ms = $7,
    max_output_bytes = $8,
    max_file_bytes = $9,
    max_sessions = $10,
    network_enabled = $11,
    approval_mode = COALESCE($12, approval_mode),
    approval_endpoint = $13,
    approval_model = $14,
    approval_timeout_ms = $15,
    approval_max_input_bytes = $16,
    approval_max_concurrent = $17,
    approval_max_output_tokens = $18,
    approval_api_key_ciphertext = $19,
    approval_api_key_nonce = $20,
    approval_api_key_key_version = $21,
    updated_at = NOW()
WHERE application_id = $1
RETURNING
    application_id,
    name,
    is_active,
    workspace_template,
    default_shell,
    created_at,
    updated_at,
    default_scopes,
    max_timeout_ms,
    max_output_bytes,
    max_file_bytes,
    max_sessions,
    network_enabled,
    approval_mode,
    approval_endpoint,
    approval_model,
    approval_timeout_ms,
    approval_max_input_bytes,
    approval_max_concurrent,
    approval_max_output_tokens,
    approval_api_key_ciphertext IS NOT NULL AS approval_api_key_configured;
